# 第1章 数据与Python语言

## 1.1数据与统计学

## 1.2Python的初步使用

### 代码框1-1 Python模块的初步使用

In [ ]:
#以下命令在cmd窗口或powershell窗口输入
#安装模块
pip install pandas
#导入模块
import numpy
#导入模块并重命名
import numpy as np
#显示已经安装模块的名称
conda list
#卸载安装在Python中的模块
conda uninstall pandas

### 代码框1-2 查看帮助

In [13]:
#从代码框1-2开始后续的代码全部在jupyter notebook中输入
help(sum)         #查看sum函数的帮助信息
help('random')      #查看模块random的帮助信息
#或
import random       #导入random模块
help(random)       #查看模块random的帮助信息
help(random.gauss)   #查看模块random中gauss函数的帮助信息


Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



### 代码框1-3 对象赋值与运行

In [3]:
x = [80, 87, 98, 73, 100]         #将5个数据组成的列表赋值给对象x
s = sum(x)                       #计算对象x的总和并赋值给对象s
n = len(x)                       #计算对象x的元素个数并赋值给n
m = s/n                          #计算对象x的平均数并赋值给对象m
print(s, n, m)

import pandas as pd
example1_1 = pd.read_csv("F:\JupyterData\Statistics_Pythoncoding\data\chap01\example1_1.csv", encoding = 'gbk')
d = example1_1                   #将数据框example1_1赋值给对象d
print(d)


438 5 87.6
     社区 性别  态度
0   A社区  男  反对
1   B社区  女  反对
2   D社区  女  反对
3   C社区  男  反对
4   A社区  男  赞成
..  ... ..  ..
75  A社区  女  反对
76  C社区  男  赞成
77  B社区  男  赞成
78  A社区  女  赞成
79  C社区  女  反对

[80 rows x 3 columns]


### 代码框1-4 创建列表

In [1]:
a = [2, 3, 4, 5]                     #生成同类型元素列表
b = ["甲", "乙", "丙", "丁"]         #元素同为字符串的列表
c = ["甲", 23, True, [1, 2, 3]]     #不同类型元素列表
d = list(range(10))               #用range函数生成等差数列，起始值为0，步长为1列表
e = list(range(100, 200, 20))       #在100-200zza之间生成数列，步长为20的列表
print(a, b, c, d, e)

[2, 3, 4, 5] ['甲', '乙', '丙', '丁'] ['甲', 23, True, [1, 2, 3]] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [100, 120, 140, 160, 180]


### 代码框1-5 列表的几种操作

In [23]:
a.append(6)                             #将数字6追加到列表a的尾部
b.insert(2, '戊')                       #在列表b的第三个位置插入戊
b.pop(1)                                #移除列表b的第二个位置元素
ab = a + b                              #将a和b连接为一个新列表
f = [2, 3, 4, 5, 2, 8]                  #创建列表f
f.sort()                                #列表的元素排序
g = ['甲','乙', '丙', '丁', '戊']       #创建列表g
g.sort()                                #列表g排序
print(a, b, ab, f, g)


[2, 3, 4, 5, 6] ['甲', '戊', '丙', '丁'] [2, 3, 4, 5, 6, '甲', '戊', '丙', '丁'] [2, 2, 3, 4, 5, 8] ['丁', '丙', '乙', '戊', '甲']


### 代码框1-6 字典的简单操作

In [9]:
dc1 = {'刘文涛':68, '王宇翔':85, '田思雨':74, '徐丽娜':88, '丁文彬':63}    #用大括号创建字典
dc1
dc1.keys()      #列表形式返回字典的键
dc1.values()     #列表形式返回字典中的值
dc1.items()      #列表形式返回字典中键值对
dc1['徐丽娜']
dc2 = dict(刘文涛 = 68, 王宇翔 = 85, 田思雨 = 74, 徐丽娜 = 88, 丁文彬 = 63)  #用dcit函数创建字典
del dc2['田思雨']
dc2
print(dc1.keys(), dc1.values(), dc1.items(), dc1['徐丽娜'], dc2)

dict_keys(['刘文涛', '王宇翔', '田思雨', '徐丽娜', '丁文彬']) dict_values([68, 85, 74, 88, 63]) dict_items([('刘文涛', 68), ('王宇翔', 85), ('田思雨', 74), ('徐丽娜', 88), ('丁文彬', 63)]) 88 {'刘文涛': 68, '王宇翔': 85, '徐丽娜': 88, '丁文彬': 63}


### 代码框1-7 创建集合与集合的一些操作

In [2]:
set1 = set([2,2,2,1,8,3,3,5,5])   #set函数创建集合
set2 = {2,2,2,1,4,3,3,5,6,6}      #使用{}创建集合
set3 = set1 | set2                #两个集合的并集
set4 = set1 & set2                #两个集合的交集
print(set1, set2, set3, set4)


{1, 2, 3, 5, 8} {1, 2, 3, 4, 5, 6} {1, 2, 3, 4, 5, 6, 8} {1, 2, 3, 5}


### 代码框1-8 创建数组和数组的一些操作

In [4]:
#创建一维数组（向量）
import numpy as np
a1 = np.array([5,4,1,2,3])   #使用array函数生成数组
a2 = np.arange(10)           #使用arange函数生成等差数列，起点0，步长1
a3 = np.arange(2,6,0.5)      #用arange函数在2-6之间生成步长为0.5的等差数列
print('a1:',a1)
print('a2:',a2)
print('a3:',a3)
a1.dtype                     #查看数据类型

a1: [5 4 1 2 3]
a2: [0 1 2 3 4 5 6 7 8 9]
a3: [2.  2.5 3.  3.5 4.  4.5 5.  5.5]


dtype('int32')

In [5]:
#创建二维数组
import numpy as np
a4 = np.array([[1,2,3],[3,4,5],[5,6,7]])
a4

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [2]:
#改变数组的形状
import numpy as np
a5 = np.arange(12)        #创建一维数组
a6 = a5.reshape(3,4)      #改变数组为3*4的二维数组
print(a5)
print(a6)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
#数组的其他操作
a6.ndim                    #查看数组a6的维度
a6.shape                   #查看数组a6的形状
a6.dtype                   #查看数组a6的数据类型
a6.astype(float)           #改变数组a6的数据类型为浮点值
a6[2]                      #访问数组a6的第三个元素
print(a6.ndim)
print(a6.shape)
print(a6.dtype )
print(a6.astype(float))
print(a6[2] )

2
(3, 4)
int32
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[ 8  9 10 11]


### 代码框1-9  用pandas创建序列

In [7]:
import pandas as pd
s1 = pd.Series([2,3,4,5])            #省略索引时自动生成索引,S要大写
s1

0    2
1    3
2    4
3    5
dtype: int64

In [8]:
s2 = pd.Series([5,8,7,6], index = ['a','b','c','d'])      #指定索引
s2

a    5
b    8
c    7
d    6
dtype: int64

In [9]:
s3 = pd.Series([60,80,50],index = ['甲',25, True])     #索引可以是不同类型元素
s3

甲       60
25      80
True    50
dtype: int64

In [10]:
s4 = pd.Series({'a':1, 'b':'boy', 'c':3})           #以字典形式生成序列
s4

a      1
b    boy
c      3
dtype: object

In [12]:
s5 = pd.Series(range(5))                         #由range函数生成序列
s5

0    0
1    1
2    2
3    3
4    4
dtype: int64

### 代码框1-10 序列的基本操作

In [3]:
#获取序列的索引、数据、类型
import pandas as pd
s6 = pd.Series([5,8,7,6], index=['a','b','c','d'])
print(s6.index)             #获取序列索引
print(s6.values)            #获取序列数据
print(s6.dtype)             #获取序列类型

Index(['a', 'b', 'c', 'd'], dtype='object')
[5 8 7 6]
int64


In [4]:
#设置序列和索引的名称
s6.name = '数列名称'      #设置序列名称
s6.index.name = '索引名称'  #设置索引名称
s6

索引名称
a    5
b    8
c    7
d    6
Name: 数列名称, dtype: int64

In [5]:
#转换序列数据类型
s6 = s6.astype(float)
s6

索引名称
a    5.0
b    8.0
c    7.0
d    6.0
Name: 数列名称, dtype: float64

In [6]:
#修改序列的数据
s6[[1,3]] = [11,15]
s6

索引名称
a     5.0
b    11.0
c     7.0
d    15.0
Name: 数列名称, dtype: float64

In [8]:
#两个序列对齐相加
s7 = pd.Series([1, 2, 3], index=['a','c','e'], dtype=float)
s6+s7

a    6.0
b    NaN
c    9.0
d    NaN
e    NaN
dtype: float64

In [11]:
#序列的简单运算
s8 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'], dtype=float)
l = s8.cumsum()  #序列的累加
h = s8.sum()     #序列求和
p = s8.mean()    #求序列的平均数
print(l)
print(h)
print(p)


a     1.0
b     3.0
c     6.0
d    10.0
e    15.0
dtype: float64
15.0
3.0


### 代码框1-11 使用字典创建数据框

In [7]:
#使用字典创建数据框（行索引自动生成）
import pandas as pd
d = {"姓名": ["刘文涛","王宇翔","田思雨","徐丽娜","丁文彬"],
"统计学": [68,85,74,88,63],
"数学": [85,91,74,100,82],
"经济学": [84,63,61,49,89]}
table1_1 = pd.DataFrame(d)     #创建数据框命名为table1_1,注意命令DataFrame大小写
table1_1

姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

### 代码框1-12 数据框常用操作

In [19]:
import pandas as pd
df = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\table1_1.csv",encoding = 'gbk')
                                       #加载数据表table1_1，并命名为df,报错：[Errno 22] Invalid argument，F:前面加了转义符r,Done
df[['数学']]                           #选择数学1列
df[['数学','统计学']]                  #选择统计学、数学2列
df.loc[2]                              #选择第3行数据
df.loc[[2,4]]                          #选择第3、5行数据
df.loc[2:4]                            #选择第3-5行数据
#df['会计学'] = [88,75,92,67,78]        #增加会计学列
#df.loc[:,'会计学']=[88,75,92,67,78]
df.insert(2,'会计学',[88,75,92,67,78])  #在第3列插入会计学
df.drop(['数学'], axis=1,inplace=True)  #删除会计学列
df.drop(index=2, inplace=True)          #删除第3行
df.rename(columns = {'经济学':'管理学','会计学':'计算机'},inplace=True)  #教材语句有问题，需增加inplace=True
#df.columns = ['姓名','统计学','计算机','管理学']     #更换列名称的另一种实现方法
df.iloc[2,1] = 90                      #将第3行，第2列徐丽娜的统计学成绩更改为90
df


姓名  统计学  计算机  管理学
0  刘文涛   68   88   84
1  王宇翔   85   75   63
3  徐丽娜   90   67   49
4  丁文彬   63   78   89

### 代码框1-13 数据框排序

In [33]:
import pandas as pd
table1_1 = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\table1_1.csv",encoding='gbk')  #在路径前面添加了r转义符
# table1_1.sort_values('统计学',inplace=True)                   #教材语句有误，需删除'by='添加',inplace=True'
# print(table1_1)
table2 = table1_1.sort_index(axis=1, ascending=False)          #按列索引字符串降序（可能是字符串长度）对数据框排序
print(table2)


   统计学  经济学   数学   姓名
0   68   84   85  刘文涛
1   85   63   91  王宇翔
2   74   61   74  田思雨
3   88   49  100  徐丽娜
4   63   89   82  丁文彬


### 代码框1-14 数据框合并

In [34]:
#按行合并数据框(按行合并时，列索引必须一致；按列合并时，行索引必须一致)
import pandas as pd
table1_1 = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\table1_1.csv",encoding='gbk')
table1_2 = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\table1_2.csv",encoding='gbk')
mytable = pd.concat([table1_1,table1_2]).reset_index(drop=True)             #合并table1_1与table1_2两个数据库
mytable

姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89
5  李志国   78   84   51
6  王智强   90   78   59
7  宋丽媛   80  100   53
8  袁芳芳   58   51   79
9  张建国   63   70   91

### 代码框1-15 生成随机数

In [19]:
#生成不同分布随机数（每种分布5个）
import numpy.random as npr
npr.seed(15)
r1 = npr.standard_normal(size=5)                #标准正态分布
r2 = npr.normal(loc=50,scale=5,size=5)          #均值为50的正态分布
r3 = npr.uniform(low=0,high=10,size=5)          #0-10之间的均匀分布
r4 = npr.chisquare(df=15,size=5)                #自由度为15的卡方分布
print('#标准正态分布:',r1)
print('#均值为50的正态分布:',r2)
print('#0-10之间的均匀分布:',r3)
print('#自由度为15的卡方分布:',r4)
print(r1,'\n',r2, '\n',r3, '\n',r4)

#标准正态分布: [-0.31232848  0.33928471 -0.15590853 -0.50178967  0.23556889]
#均值为50的正态分布: [41.18197372 44.52068978 44.56117129 48.47414974 47.63125814]
#0-10之间的均匀分布: [9.17629898 2.64146853 7.17773687 8.65715034 8.07079482]
#自由度为15的卡方分布: [11.65749531 11.98507727 22.67529789 11.13672652  9.05412533]
[-0.31232848  0.33928471 -0.15590853 -0.50178967  0.23556889] 
 [41.18197372 44.52068978 44.56117129 48.47414974 47.63125814] 
 [9.17629898 2.64146853 7.17773687 8.65715034 8.07079482] 
 [11.65749531 11.98507727 22.67529789 11.13672652  9.05412533]


### 代码框1-16 数据抽样

In [24]:
import random
a = range(1,21)                                     #生成1-20数值序列
n1 = random.sample(population=a, k=10); n1          #无放回抽取10个数据
n2 = random.choices(population=a, k=10); n2         #有放回抽取10个数值
ncols = ["black","red","green","blue","yellow"]     #5种不同颜色列表
ncols=random.choices(ncols, k=6);ncols              #有放回抽取6次
print('#无放回抽取:','\n',n1,'\n''#有放回抽取:','\n',n2,'\n''#有放回抽样6次:','\n',ncols)  #'\n'是python换行符，每次运行都会得到不同结果

#无放回抽取: 
 [14, 5, 2, 9, 16, 15, 13, 19, 11, 4] 
#有放回抽取: 
 [15, 13, 2, 20, 11, 12, 3, 3, 5, 18] 
#有放回抽样6次: 
 ['green', 'red', 'blue', 'green', 'red', 'blue']


### 代码框1-17 读取数据

In [26]:
#读取csv格式数据
import pandas as pd
table1_1 = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\table1_1.csv",encoding='gbk')
table1_1

姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [27]:
#读取excel格式数据
import pandas as pd
df = pd.read_excel(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\table1_1.xlsx")
df

姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

### 代码框1-18 保存数据

In [30]:
#将数据保存为csv格式，并存放在制定路径
import pandas as pd
table1_1.to_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\df1.csv",index=False,encoding='gbk')   #格式设置为'gbk'，‘utf-8’格式出现乱码

In [29]:
#将数据保存为EExcel格式，并存放在制定路径
table1_1.to_excel(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\df2.xlsx",index=False,encoding='utf-8')
#index参数默认为True,设置为False表示不保存行索引

### 代码框1-19 生产单变量一维表

In [3]:
#使用value.count()函数生成一维频数表
import pandas as pd
example1_1 = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\example1_1.csv",encoding='gbk')
print(example1_1)
example1_1['社区'].value_counts()        #生产频数表（类型是序列）

     社区 性别  态度
0   A社区  男  反对
1   B社区  女  反对
2   D社区  女  反对
3   C社区  男  反对
4   A社区  男  赞成
..  ... ..  ..
75  A社区  女  反对
76  C社区  男  赞成
77  B社区  男  赞成
78  A社区  女  赞成
79  C社区  女  反对

[80 rows x 3 columns]


A社区    27
C社区    21
B社区    17
D社区    15
Name: 社区, dtype: int64

In [4]:
#将频数表转化为百分比表
example1_1['社区'].value_counts(normalize=True)*100

A社区    33.75
C社区    26.25
B社区    21.25
D社区    18.75
Name: 社区, dtype: float64

### 代码框1-20 生成两变量的二维表

In [5]:
#使用pd中的crosstab函数生成二维表
import pandas as pd
df = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\example1_1.csv",encoding='gbk')
tab1 = pd.crosstab(df.社区,df.态度)
tab1

态度   反对  赞成
社区         
A社区  13  14
B社区   5  12
C社区   7  14
D社区   6   9

In [8]:
#为二维表添加边际和，并修改边际和的名称
tab2 = pd.crosstab(df.社区,df.态度, margins=True, margins_name='合计')
tab2

态度   反对  赞成  合计
社区             
A社区  13  14  27
B社区   5  12  17
C社区   7  14  21
D社区   6   9  15
合计   31  49  80

In [13]:
#将二维表转化成百分比表
tab3 = pd.crosstab(df.社区,df.态度,margins=True,margins_name='合计',normalize='index')    #按行转化为百分比
round(tab3*100,2)

态度      反对     赞成
社区               
A社区  48.15  51.85
B社区  29.41  70.59
C社区  33.33  66.67
D社区  40.00  60.00
合计   38.75  61.25

In [14]:
#计算各列所占比例，并转化成百分比表
tab4 = pd.crosstab(df.社区,df.态度,margins=True,margins_name='合计',normalize='columns')
round(tab4*100,2)

态度      反对     赞成     合计
社区                      
A社区  41.94  28.57  33.75
B社区  16.13  24.49  21.25
C社区  22.58  28.57  26.25
D社区  19.35  18.37  18.75

In [15]:
#计算各数据占总和的比例，并转化成百分比表
tab5 = pd.crosstab(df.社区,df.态度,margins=True,margins_name='合计',normalize='all')
tab5*100

态度      反对     赞成      合计
社区                       
A社区  16.25  17.50   33.75
B社区   6.25  15.00   21.25
C社区   8.75  17.50   26.25
D社区   7.50  11.25   18.75
合计   38.75  61.25  100.00

### 代码框1-21 生成多维表

In [16]:
#社区和性别为行变量，态度为列变量
import pandas as pd
import numpy as np
df = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\example1_1.csv",encoding='gbk')
tab = pd.pivot_table(df,index=['社区','性别'],columns=['态度'],margins=True,margins_name='合计',aggfunc=len)
tab

态度      反对  赞成  合计
社区  性别            
A社区 女    9   9  18
    男    4   5   9
B社区 女    2   5   7
    男    3   7  10
C社区 女    2   6   8
    男    5   8  13
D社区 女    4   7  11
    男    2   2   4
合计      31  49  80

In [17]:
#性别和态度为行变量，社区为列变量
tab = pd.pivot_table(df,index=['性别','态度'],columns=['社区'],margins=True,margins_name='合计',aggfunc=len)
tab

社区     A社区  B社区  C社区  D社区  合计
性别 态度                        
女  反对    9    2    2    4  17
   赞成    9    5    6    7  27
男  反对    4    3    5    2  14
   赞成    5    7    8    2  22
合计      27   17   21   15  80

In [18]:
#社区为行变量、性别和态度为列变量
tab = pd.pivot_table(df,index=['社区'],columns=['性别','态度'],margins=True,margins_name='合计',aggfunc=len)
tab

性别    女       男      合计
态度   反对  赞成  反对  赞成    
社区                     
A社区   9   9   4   5  27
B社区   2   5   3   7  17
C社区   2   6   5   8  21
D社区   4   7   2   2  15
合计   17  27  14  22  80

### 代码框1-22 数据分组与生成频数分布表

In [20]:
import pandas as pd
df = pd.read_csv(r"F:\JupyterData\Statistics_Pythoncoding\data\chap01\example1_2.csv",encoding='gbk')
f = pd.cut(df['销售额'],
          bins = [160,170,180,190,200,210,220,230,240,250,260,270,280],
          right=False)               #分组不含上限值
tf = f.value_counts()                #生成频数表
tab = tf.sort_index()                 #按索引排序
tab.index.name = '销售额分组'        #添加索引名称
tab

销售额分组
[160, 170)     2
[170, 180)     4
[180, 190)     7
[190, 200)    17
[200, 210)    27
[210, 220)    20
[220, 230)    16
[230, 240)    13
[240, 250)     7
[250, 260)     4
[260, 270)     2
[270, 280)     1
Name: 销售额, dtype: int64